[project]
name = "courses"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.5"
dependencies = [
    "django>=5.2.4",
    "django-mptt>=0.17.0",
    "pillow>=11.3.0",
    "psycopg2-binary>=2.9.10",
    "python-slugify>=8.0.4",
]
